cityWidth: 16
cityHeight: 16
tileTypes:
  0:
    type: empty
    name: Empty
    color: '#4a4a4a'
    editorIcon: 'static/fa/times-solid.svg'
  1:
    type: road
    name: Road
    color: '#8f8f8f'
    editorIcon: 'static/fa/road-solid.svg'
    emissions: 0.1
  2:
    type: residential
    name: Residential
    color: '#ff8787'
    editorIcon: 'static/fa/home-solid.svg'
  3:
    type: industrial
    name: Industrial
    color: '#ffeb78'
    editorIcon: 'static/fa/industry-solid.svg'
    emissions: 0.3
  4:
    type: commercial
    name: Commercial
    color: '#84aeff'
    editorIcon: 'static/fa/building-regular.svg'
  5:
    type: park
    name: Park
    color: '#44a740'
    editorIcon: 'static/fa/tree-solid.svg'
    emissions: -0.2
  6:
    type: water
    name: Water
    color: '#38c4ee'
    editorIcon: 'static/fa/water-solid.svg'
carTypes:
  car-blue:
    maxSpeed: 1
    frequency: 1
  car-white:
    maxSpeed: 1.2
    frequency: 0.5
  car-red:
    maxSpeed: 1.1
    frequency: 1
  truck-white:
    maxSpeed: 0.85
    frequency: 0.2
    lanes: inner
  pickup-aqua:
    maxSpeed: 1
    frequency: 0.5
  van-white:
    maxSpeed: 1
    frequency: 0.7
  bus-yellow:
    maxSpeed: 0.9
    frequency: 0.3
    lanes: outer
  tram:
    maxSpeed: 0.8
    frequency: 0.3
    lanes: inner
    wagons: [tram, tram]

