cityWidth: 16
cityHeight: 16
tileTypes:
  0:
    name: Empty
    color: '#4a4a4a'
    editorIcon: 'static/fa/times-solid.svg'
  1:
    name: Road
    color: '#8f8f8f'
    editorIcon: 'static/fa/road-solid.svg'
    emissions: 0.1
  2:
    name: Residential
    color: '#e27f7f'
    editorIcon: 'static/fa/home-solid.svg'
  3:
    name: Industrial
    color: '#e2ce7f'
    editorIcon: 'static/fa/industry-solid.svg'
    emissions: 0.3
  4:
    name: Commercial
    color: '#7fb2e2'
    editorIcon: 'static/fa/building-regular.svg'
  5:
    name: Park
    color: '#3bab40'
    editorIcon: 'static/fa/tree-solid.svg'
    emissions: -0.2
  6:
    name: Water
    color: '#32d3c2'
    editorIcon: 'static/fa/water-solid.svg'
