tileTypes:
  #5:
  0:
    type: park
    name: Park
    color: "#2ee517"
    editorIcon: "static/fa/tree-solid.svg"
  1:
    type: road
    name: Road
    color: "#8f8f8f"
    editorIcon: "static/fa/road-solid.svg"
    emissions: 0.1
    noise: 0.20
  2:
    type: residential
    name: Residential
    color: "#fd6451"
    editorIcon: "static/fa/home-solid.svg"
    noise: 0.05
  3:
    type: water
    name: Water
    color: "#19fff7"
    editorIcon: "static/fa/water-solid.svg"
