variables:
  green-spaces:
    name:
      de: Freifläche
      en: Green spaces
  wind-turbines:
    name:
      de: Energieversorgung
      en: Energy supply
  distances:
    name:
      de: Abstände
      en: Distances
  life-span:
    name:
      de: Lebensdauer
      en: Life span
