wind:
  winddirection:
    id: "wind_direction"
    name_de: "Windrichtung"
    name_en: "Winddirection"
    divisions: 8
    labels: ["N", "NO", "O", "SO", "S", "SW", "W", "NW"]
    default: "N"
  windspeed:
    id: "wind_speed"
    name_de: Windgeschwindigkeit
    name_en: Windspeed
    divisions: null
    labels: null
    default: "0 km/h"
    starting_speed: "10 km/h"
