wind:
  winddirection:
    id: "wind_direction"
    name_de: "Windrichtung"
    name_en: "Winddirection"
    divisions: 4
    labels: ["N", "O", "S", "W"]
    default: "N"
  windspeed:
    id: "wind_speed"
    name_de: Windgeschwindigkeit
    name_en: Windspeed
    divisions: null
    labels: null
    default: "0 km/h"
    starting_speed: 9
    max_speed: 90
