$schema: https://json-schema.org/draft/2020-12/schema
$id: https://imaginary.github.io/future-mobility/docs/specs/config.schema.yaml
summary: Future of Mobility configuration schema
type: object
properties:
  cityWidth:
    type: integer
    title: Width (in tiles) of the city map.
    minimum: 1
  cityHeight:
    type: integer
    title: Height (in tiles) of the city map.
    minimum: 1
  tileTypes:
    type: object
    title: Tile type definitions
    patternProperties:
      "^(0|[1-9][0-9]*)$":
        type: object
        properties:
          name:
            type: string
            title: Tile type name
          color:
            type: string
            title: Tile type color
            format: "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"
          editorIcon
            type: string
            title: Path to the icon to use in the map editor for this tile type
          emissions:
            type: number
            minimum: -1
            maximum: 1
            title: CO2 emission index of tiles of this type
            description: |
              CO2 emission index of tiles of this type
              - 0 means no emissons.
              - 1 is maximum emissions.
              - Negative means the tile absorbs emissions around it.
        required: [ name, color ]
required: [ cityWidth, cityHeight, tileTypes ]
